### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Minephoenixlive** [Brian-Wuest/MC-Prefab#273]
### Minecraft Version

1.19.2

### Forge Version

forge43.1.43

### Mod Version

1.19.2-1.0.457-ALPHA

### Details

When I select a structure for minecolonies, the preview at the menu does not appear. But when I look at the structure outside of the preview menu, it is there.
Here is a list of all mods i using:
Mods:
  [✔️] AE2Things-1.1.1-beta.1
  [✔️] AEInfinityBooster-1.19.2-1.2.0+11
  [✔️] angelring-1.19-2.1.3
  [✔️] antighost-1.19.1-forge42.0.1-1.1.2
  [✔️] appliedenergistics2-forge-12.8.2-beta
  [✔️] Applied-Mekanistics-1.3.2
  [✔️] architectury-6.2.46-forge
  [✔️] AutoRegLib-1.8-54
  [✔️] balm-4.5.3
  [✔️] blockui-1.19-0.0.64-ALPHA
  [✔️] Bookshelf-Forge-1.19.2-16.1.5
  [✔️] BotanyPots-Forge-1.19.2-9.0.7
  [✔️] caelus-forge-1.19.2-3.0.0.6
  [✔️] cloth-config-8.2.88-forge
  [✔️] configured-2.0.1-1.19.2
  [✔️] constructionwand-1.19.1-2.8
  [✔️] craftingtweaks-forge-1.19-15.1.0
  [✔️] create-1.19.2-0.5.0.f
  [✔️] Cucumber-1.19.2-6.0.2
  [✔️] curios-forge-1.19.2-5.1.1.0
  [✔️] domum_ornamentum-1.19-1.0.59-ALPHA-universal
  [✔️] ecologics-forge-1.19.2-2.1.10
  [✔️] elytraslot-forge-6.0.0+1.19.2
  [✔️] FluxNetworks-1.19.2-7.1.1.10
  [✔️] ftb-chunks-forge-1902.3.9-build.168
  [✔️] ftb-essentials-1902.1.10-build.47
  [✔️] ftb-library-forge-1902.3.9-build.144 (1)
  [✔️] ftb-quests-forge-1902.4.2-build.116
  [✔️] ftb-teams-forge-1902.2.9-build.61
  [✔️] ftb-ultimine-forge-1902.3.5-build.65
  [✔️] ImmersiveEngineering-1.19.2-9.0.0-153
  [✔️] ironfurnaces-1.19.2-3.6.3
  [✔️] IronJetpacks-1.19.1-6.0.0
  [✔️] item-filters-forge-1902.2.9-build.41
  [✔️] jei-1.19.2-forge-11.3.0.262
  [✔️] jmi-forge-1.19.2-0.13-30
  [✔️] journeymap-1.19.1-5.9.0beta2-forge
  [✔️] light-overlay-7.0.1-forge
  [✔️] Mekanism-1.19.2-10.3.4.471
  [✔️] MekanismGenerators-1.19.2-10.3.4.471
  [✔️] MekanismTools-1.19.2-10.3.4.471
  [✔️] minecolonies-1.19.2-1.0.1071-ALPHA
  [✔️] ModernUI-1.19.2-3.6.1.115-universal
  [✔️] multi-piston-1.19-1.2.16-ALPHA
  [✔️] MysticalAgradditions-1.19.1-6.0.0
  [✔️] MysticalAgriculture-1.19.2-6.0.3
  [✔️] MysticalCustomization-1.19.1-4.0.0
  [✔️] NaturesCompass-1.19.2-1.9.7-forge
  [✔️] Powah-4.0.4-beta
  [✔️] Quark-3.3-371
  [✔️] shutupexperimentalsettings-1.0.5
  [✔️] sophisticatedbackpacks-1.19.2-3.18.29.719
  [✔️] sophisticatedcore-1.19.2-0.5.13.134
  [✔️] sophisticatedstorage-1.19.2-0.5.18.151
  [✔️] structurize-1.19.2-1.0.457-ALPHA
  [✔️] TerraBlender-forge-1.19.2-2.0.1.127
  [✔️] theoneprobe-1.19-6.2.2
and now a few screenchot of my problem:
https://www.dropbox.com/s/bpm5vx6pg7ee8jw/javaw_vonj4a3DFZ.png?dl=0
https://www.dropbox.com/s/ao729zzlhgz8e8l/javaw_C63NgEmfty.png?dl=0
https://www.dropbox.com/s/a15cwuog4n3bfpd/javaw_MJpzljQqBt.png?dl=0
https://www.dropbox.com/s/j6hsm08dnt0tekd/javaw_Y5rD00D4yd.png?dl=0
and i found an error in the console about that
[22:44:49] [Structurize IO Worker #0/ERROR] [structurize/]: Error loading blueprint: 
java.io.FileNotFoundException: null
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at cpw.mods.niofs.union.UnionFileSystem.newReadByteChannel(UnionFileSystem.java:308) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.niofs.union.UnionFileSystemProvider.newByteChannel(UnionFileSystemProvider.java:149) ~[securejarhandler-2.1.4.jar:?] {}
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?] {}
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?] {}
	at java.nio.file.Files.readAllBytes(Files.java:3288) ~[?:?] {}
	at com.ldtteam.structurize.storage.StructurePacks.getBlueprint(StructurePacks.java:437) ~[structurize-1.19.2-1.0.457-ALPHA.jar%23177!/:1.19.2-1.0.457-ALPHA] {re:classloading}
	at com.ldtteam.structurize.storage.StructurePacks.getBlueprint(StructurePacks.java:423) ~[structurize-1.19.2-1.0.457-ALPHA.jar%23177!/:1.19.2-1.0.457-ALPHA] {re:classloading}
	at com.ldtteam.structurize.storage.StructurePacks.getBlueprint(StructurePacks.java:234) ~[structurize-1.19.2-1.0.457-ALPHA.jar%23177!/:1.19.2-1.0.457-ALPHA] {re:classloading}
	at com.ldtteam.structurize.storage.StructurePacks.lambda$getBlueprintFuture$0(StructurePacks.java:130) ~[structurize-1.19.2-1.0.457-ALPHA.jar%23177!/:1.19.2-1.0.457-ALPHA] {re:classloading}
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] {}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
[22:44:50] [Render thread/ERROR] [journeymap/]: Can't get entityTexture for translation{key='entity.ecologics.coconut_crab', args=[]} (SUPPRESSED)
[22:44:50] [Render thread/WARN] [journeymap/]: java.lang.Throwable: Can't get entityTexture for translation{key='entity.ecologics.coconut_crab', args=[]}

**Comment by Minephoenixlive** [comment]
sorry i have send it to the wrong mod

**Comment by Brian-Wuest** [comment]
Okay, closing issue
